modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory

license="https://github.com/Yokohama-Miyazawa/MaidIllagerForge/blob/main/LICENSE"

[[mods]]
modId="maidillager"
version="0.1.1"
displayName="MaidIllager"
authors="Yokohama-Miyazawa"
description='''
邪悪な村人の見た目が若干変わるMOD
'''
logoFile = "icon.png"

[[dependencies.maidillager]] #optional
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.maidillager]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
